version: "3.7"

services:
  lx_autonomy:
    build:
      context: ./
      dockerfile: ./docker/lx_autonomy.Dockerfile

    container_name: lx_autonomy

    privileged: true

    network_mode: host

    volumes:
      - ./src/lx_autonomy/src/:/home/lx_autonomy/lx_autonomy_ws/src/
      - ./utilities/:/home/lx_autonomy/lx_autonomy_ws/utilities/
      - /dev/:/dev/

    tty: true
    stdin_open: true

  lx_hardware:
    build:
      context: ./
      dockerfile: ./docker/lx_hardware.Dockerfile

    container_name: lx_hardware

    environment:
      DISPLAY: ${DISPLAY}

    privileged: true

    volumes:
      - ./src/lx_hardware/ros2_ws/src/lx_packages/:/home/lx_hardware/ros2_ws/src/lx_packages/
      - ./src/lx_hardware/ros1_ws/src/lx_packages/:/home/lx_hardware/ros1_ws/src/lx_packages/
      - ./src/lx_hardware/run_hardware.sh:/home/lx_hardware/run_hardware.sh
      - /dev/:/dev/
      - /tmp/.X11-unix:/tmp/.X11-unix


    tty: true
    stdin_open: true