#!/bin/sh

echo -e "\x1B[01;93m___________________________________________________________________" 
echo -e "\033[1;97m                            Welcome!"
echo -e "\033[1;97m     Project - Lunar Autonomous Regolith Excavator [ LunAR-X ]"
echo -e "\x1B[01;91m                   Carnegie Mellon University"
echo -e "\x1B[01;91m                       Robotics Institute"
echo -e "\x1B[01;93m                                          XXXXX        XXXXX"
echo -e "\033[1;97m       _                          _____   \x1B[01;93m X:::X     X:::X"
echo -e "\033[1;97m      | |                   /\   |  __ \  \x1B[01;93m  X:::X  X:::X"
echo -e "\033[1;97m      | |    _   _ _ __    /  \  | |__) | \x1B[01;93m   X:::X:::X"
echo -e "\033[1;97m      | |   | | | | '_ \  / /\ \ |  _  /  \x1B[01;93m    X:::::X"
echo -e "\033[1;97m      | |___| |_| | | | |/ ____ \| | \ \  \x1B[01;93m  X:::XX:::X"
echo -e "\033[1;97m      |______\__,_|_| |_/_/    \_\_|  \_\ \x1B[01;93mX:::X   X:::X"
echo -e "\x1B[01;93m                                        X:::X      X:::X"
echo -e "\x1B[01;93m                                      XXXXX         XXXXX"
echo -e " "
echo -e "\033[1;97m                      • Reshape The Moon •"
echo -e "\x1B[01;93m___________________________________________________________________"
echo -e "\033[0;37m" 